<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class APIKeyPair
{
    /**
     * The ID for the API key pair.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The unique thumbprint that identifies the API key pair.
     *
     * @var string $thumbprint
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('thumbprint')]
    public string $thumbprint;

    /**
     * The display name for the API key pair.
     *
     * @var string $displayName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('display_name')]
    public string $displayName;

    /**
     *
     * @var string $algorithm
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('algorithm')]
    public string $algorithm;

    /**
     * Whether the API key pair is active and can be used to authenticate.
     *
     * @var bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    public bool $active;

    /**
     * The date and time when this API key pair was created.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The date and time when this API key pair was last updated.
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public \DateTime $updatedAt;

    /**
     * The merchant accounts this API key pair has access to. An empty list means it has access to all merchant accounts.
     *
     * @var ?array<\Gr4vy\MerchantAccountSummary> $merchantAccounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchant_accounts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gr4vy\MerchantAccountSummary>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $merchantAccounts = null;

    /**
     * The roles assigned to this API key pair.
     *
     * @var ?array<\Gr4vy\Role> $roles
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('roles')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gr4vy\Role>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $roles = null;

    /**
     * The PEM-encoded private key. Only returned once, in the response to creating the API key pair, and only when Gr4vy generated the key pair. Store it securely, as it cannot be retrieved later.
     *
     * @var ?string $privateKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('private_key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $privateKey = null;

    /**
     * The user or API key pair that created this API key pair.
     *
     * @var ?\Gr4vy\ApiRoutersApiKeyPairsSchemasCreator $creator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('creator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\ApiRoutersApiKeyPairsSchemasCreator|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ApiRoutersApiKeyPairsSchemasCreator $creator = null;

    /**
     * The type of this resource.
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * @param  string  $id
     * @param  string  $thumbprint
     * @param  string  $displayName
     * @param  string  $algorithm
     * @param  bool  $active
     * @param  \DateTime  $createdAt
     * @param  \DateTime  $updatedAt
     * @param  ?string  $type
     * @param  ?array<\Gr4vy\MerchantAccountSummary>  $merchantAccounts
     * @param  ?array<\Gr4vy\Role>  $roles
     * @param  ?string  $privateKey
     * @param  ?\Gr4vy\ApiRoutersApiKeyPairsSchemasCreator  $creator
     * @phpstan-pure
     */
    public function __construct(string $id, string $thumbprint, string $displayName, string $algorithm, bool $active, \DateTime $createdAt, \DateTime $updatedAt, ?array $merchantAccounts = null, ?array $roles = null, ?string $privateKey = null, ?ApiRoutersApiKeyPairsSchemasCreator $creator = null, ?string $type = 'api-key-pair')
    {
        $this->id = $id;
        $this->thumbprint = $thumbprint;
        $this->displayName = $displayName;
        $this->algorithm = $algorithm;
        $this->active = $active;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->merchantAccounts = $merchantAccounts;
        $this->roles = $roles;
        $this->privateKey = $privateKey;
        $this->creator = $creator;
        $this->type = $type;
    }
}