<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class CheckoutSession
{
    /**
     * The ID for the checkout session.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The date and time when this checkout session expires.
     *
     * @var \DateTime $expiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires_at')]
    public \DateTime $expiresAt;

    /**
     * An array of cart items that represents the line items of a transaction.
     *
     * @var ?array<CartItem> $cartItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cart_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gr4vy\CartItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $cartItems = null;

    /**
     * Any additional information about the transaction that you would like to store as key-value pairs. This data is passed to payment service providers that support it.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Provide buyer details for the transaction. No buyer resource will be created on Gr4vy when used.
     *
     * @var ?GuestBuyer $buyer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('buyer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\GuestBuyer|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GuestBuyer $buyer = null;

    /**
     * The airline addendum data which describes the airline booking associated with this transaction.
     *
     * @var ?Airline $airline
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('airline')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\Airline|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Airline $airline = null;

    /**
     * The total amount for this transaction.
     *
     * @var ?int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $amount = null;

    /**
     * The currency code for this transaction.
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * The unique identifier of an existing payment service. When provided, the created transaction will be processed by the given payment service and any routing rules will be skipped.
     *
     * @var ?string $paymentServiceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_service_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $paymentServiceId = null;

    /**
     * Information about the payment method stored on the checkout session.
     *
     * @var ?CheckoutSessionPaymentMethod $paymentMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_method')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\CheckoutSessionPaymentMethod|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CheckoutSessionPaymentMethod $paymentMethod = null;

    /**
     * Always `checkout-session`
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * @param  string  $id
     * @param  \DateTime  $expiresAt
     * @param  ?string  $type
     * @param  ?array<CartItem>  $cartItems
     * @param  ?array<string, string>  $metadata
     * @param  ?GuestBuyer  $buyer
     * @param  ?Airline  $airline
     * @param  ?int  $amount
     * @param  ?string  $currency
     * @param  ?string  $paymentServiceId
     * @param  ?CheckoutSessionPaymentMethod  $paymentMethod
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $expiresAt, ?array $cartItems = null, ?array $metadata = null, ?GuestBuyer $buyer = null, ?Airline $airline = null, ?int $amount = null, ?string $currency = null, ?string $paymentServiceId = null, ?CheckoutSessionPaymentMethod $paymentMethod = null, ?string $type = 'checkout-session')
    {
        $this->id = $id;
        $this->expiresAt = $expiresAt;
        $this->cartItems = $cartItems;
        $this->metadata = $metadata;
        $this->buyer = $buyer;
        $this->airline = $airline;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->paymentServiceId = $paymentServiceId;
        $this->paymentMethod = $paymentMethod;
        $this->type = $type;
    }
}