<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class ConnectionOptions
{
    /**
     * Custom options for `checkout-card` payment service.
     *
     * @var ?CheckoutCardConnectionOptions $checkoutCard
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkout-card')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\CheckoutCardConnectionOptions|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CheckoutCardConnectionOptions $checkoutCard = null;

    /**
     * @param  ?CheckoutCardConnectionOptions  $checkoutCard
     * @phpstan-pure
     */
    public function __construct(?CheckoutCardConnectionOptions $checkoutCard = null)
    {
        $this->checkoutCard = $checkoutCard;
    }
}