<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;

use Gr4vy\Utils\SpeakeasyMetadata;
class CreatePaymentMethodRequest
{
    /**
     *
     * @var CardPaymentMethodCreate|RedirectPaymentMethodCreate|CheckoutSessionPaymentMethodCreate $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public CardPaymentMethodCreate|RedirectPaymentMethodCreate|CheckoutSessionPaymentMethodCreate $requestBody;

    /**
     * The ID of the merchant account to use for this request.
     *
     * @var ?string $merchantAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-gr4vy-merchant-account-id')]
    public ?string $merchantAccountId = null;

    /**
     *
     * @var ?float $timeoutInSeconds
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=timeout_in_seconds')]
    public ?float $timeoutInSeconds = null;

    /**
     * @param  CardPaymentMethodCreate|RedirectPaymentMethodCreate|CheckoutSessionPaymentMethodCreate  $requestBody
     * @param  ?float  $timeoutInSeconds
     * @param  ?string  $merchantAccountId
     * @phpstan-pure
     */
    public function __construct(CardPaymentMethodCreate|RedirectPaymentMethodCreate|CheckoutSessionPaymentMethodCreate $requestBody, ?string $merchantAccountId = null, ?float $timeoutInSeconds = 1)
    {
        $this->requestBody = $requestBody;
        $this->merchantAccountId = $merchantAccountId;
        $this->timeoutInSeconds = $timeoutInSeconds;
    }
}