<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;

use Gr4vy\Utils\SpeakeasyMetadata;
class DeleteThreeDsScenarioRequest
{
    /**
     * The ID of the 3DS scenario
     *
     * @var string $threeDsScenarioId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=three_ds_scenario_id')]
    public string $threeDsScenarioId;

    /**
     * The ID of the merchant account to use for this request.
     *
     * @var ?string $merchantAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-gr4vy-merchant-account-id')]
    public ?string $merchantAccountId = null;

    /**
     * @param  string  $threeDsScenarioId
     * @param  ?string  $merchantAccountId
     * @phpstan-pure
     */
    public function __construct(string $threeDsScenarioId, ?string $merchantAccountId = null)
    {
        $this->threeDsScenarioId = $threeDsScenarioId;
        $this->merchantAccountId = $merchantAccountId;
    }
}