<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class ErrorDetail
{
    /**
     *
     * @var string $location
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location')]
    public string $location;

    /**
     * A JSON pointer for the particular property that caused the error.
     *
     * @var string $pointer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pointer')]
    public string $pointer;

    /**
     * A human-readdable explanation of the error.
     *
     * @var string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    public string $message;

    /**
     * The type of error that was raised for this property.
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $location
     * @param  string  $pointer
     * @param  string  $message
     * @param  string  $type
     * @phpstan-pure
     */
    public function __construct(string $location, string $pointer, string $message, string $type)
    {
        $this->location = $location;
        $this->pointer = $pointer;
        $this->message = $message;
        $this->type = $type;
    }
}