<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


/** GiftCardIssuanceCreate - The details used to issue a new virtual gift card. */
class GiftCardIssuanceCreate
{
    /**
     * The provider theme code to issue the gift card against.
     *
     * @var string $theme
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('theme')]
    public string $theme;

    /**
     * The amount to load onto the gift card, in the smallest denomination for the currency.
     *
     * @var int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     * The ISO-4217 currency code for the `amount`.
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * An optional external identifier for this issuance.
     *
     * @var ?string $externalIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalIdentifier = null;

    /**
     * @param  string  $theme
     * @param  int  $amount
     * @param  string  $currency
     * @param  ?string  $externalIdentifier
     * @phpstan-pure
     */
    public function __construct(string $theme, int $amount, string $currency, ?string $externalIdentifier = null)
    {
        $this->theme = $theme;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->externalIdentifier = $externalIdentifier;
    }
}