<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;

use Gr4vy\Utils\SpeakeasyMetadata;
class IssueGiftCardRequest
{
    /**
     *
     * @var \Gr4vy\GiftCardIssuanceCreate $giftCardIssuanceCreate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public GiftCardIssuanceCreate $giftCardIssuanceCreate;

    /**
     * The ID of the merchant account to use for this request.
     *
     * @var ?string $merchantAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-gr4vy-merchant-account-id')]
    public ?string $merchantAccountId = null;

    /**
     * A unique key forwarded to the gift card service to make the issuance idempotent.
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=idempotency-key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  \Gr4vy\GiftCardIssuanceCreate  $giftCardIssuanceCreate
     * @param  ?string  $merchantAccountId
     * @param  ?string  $idempotencyKey
     * @phpstan-pure
     */
    public function __construct(GiftCardIssuanceCreate $giftCardIssuanceCreate, ?string $merchantAccountId = null, ?string $idempotencyKey = null)
    {
        $this->giftCardIssuanceCreate = $giftCardIssuanceCreate;
        $this->merchantAccountId = $merchantAccountId;
        $this->idempotencyKey = $idempotencyKey;
    }
}