<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class KlarnaSubscriptionOptions
{
    /**
     * The name of the subscription product. The recommended format includes a subscription id and double curly brackets.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The cadence unit for the subscription plan.
     *
     * @var string $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    public string $interval;

    /**
     * The number corresponding to the interval unit.
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval_count')]
    public int $intervalCount;

    /**
     * Reference to a SKU in the transaction's cart items to link subscription to.
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     * @param  string  $name
     * @param  string  $interval
     * @param  int  $intervalCount
     * @param  string  $reference
     * @phpstan-pure
     */
    public function __construct(string $name, string $interval, int $intervalCount, string $reference)
    {
        $this->name = $name;
        $this->interval = $interval;
        $this->intervalCount = $intervalCount;
        $this->reference = $reference;
    }
}