<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class PaymentMethodCard
{
    /**
     * The 13-19 digit number for this card as it can be found on the front of the card.
     *
     * @var string $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    public string $number;

    /**
     * The expiration date of the card, formatted `MM/YY`.
     *
     * @var string $expirationDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiration_date')]
    public string $expirationDate;

    /**
     * The optional card's network scheme.
     *
     * @var ?CardScheme $cardScheme
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('card_scheme')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\CardScheme|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardScheme $cardScheme = null;

    /**
     * The merchant identifier for this card.
     *
     * @var ?string $externalIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalIdentifier = null;

    /**
     * Set to `card` to use a new card.
     *
     * @var ?string $method
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('method')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $method = null;

    /**
     * @param  string  $number
     * @param  string  $expirationDate
     * @param  ?string  $method
     * @param  ?CardScheme  $cardScheme
     * @param  ?string  $externalIdentifier
     * @phpstan-pure
     */
    public function __construct(string $number, string $expirationDate, ?CardScheme $cardScheme = null, ?string $externalIdentifier = null, ?string $method = 'card')
    {
        $this->number = $number;
        $this->expirationDate = $expirationDate;
        $this->cardScheme = $cardScheme;
        $this->externalIdentifier = $externalIdentifier;
        $this->method = $method;
    }
}