<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class PaypalShippingOptions
{
    /**
     * Shipping options that the payee or merchant offers to the payer to ship or pick up their items.
     *
     * @var ?array<PaypalShippingOptionsItem> $options
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('options')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gr4vy\PaypalShippingOptionsItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $options = null;

    /**
     * @param  ?array<PaypalShippingOptionsItem>  $options
     * @phpstan-pure
     */
    public function __construct(?array $options = null)
    {
        $this->options = $options;
    }
}