<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class PazeMobileSession
{
    /**
     * The Paze merchant data ID.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The merchant display name.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The Paze profile ID for the given domain.
     *
     * @var string $profileId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profileId')]
    public string $profileId;

    /**
     * The Paze OAuth access token. Returned only when `source` is `mobile`.
     *
     * @var string $accessToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accessToken')]
    public string $accessToken;

    /**
     * The Paze session ID. Returned only when `source` is `mobile`.
     *
     * @var string $sessionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sessionId')]
    public string $sessionId;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  string  $profileId
     * @param  string  $accessToken
     * @param  string  $sessionId
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, string $profileId, string $accessToken, string $sessionId)
    {
        $this->id = $id;
        $this->name = $name;
        $this->profileId = $profileId;
        $this->accessToken = $accessToken;
        $this->sessionId = $sessionId;
    }
}