<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class PazeSessionReview
{
    /**
     *
     * @var \Gr4vy\PazeConsumer $consumer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consumer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\PazeConsumer')]
    public PazeConsumer $consumer;

    /**
     *
     * @var \Gr4vy\PazeMaskedCard $maskedCard
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maskedCard')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\PazeMaskedCard')]
    public PazeMaskedCard $maskedCard;

    /**
     *
     * @var \Gr4vy\PazeSessionReviewLinks $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('links')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\PazeSessionReviewLinks')]
    public PazeSessionReviewLinks $links;

    /**
     * Opaque token issued by the Paze service to be used in the next Paze interaction.
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var ?\Gr4vy\PazeShippingAddress $shippingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shippingAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gr4vy\PazeShippingAddress|null')]
    public ?PazeShippingAddress $shippingAddress;

    /**
     * @param  \Gr4vy\PazeConsumer  $consumer
     * @param  \Gr4vy\PazeMaskedCard  $maskedCard
     * @param  \Gr4vy\PazeSessionReviewLinks  $links
     * @param  string  $code
     * @param  ?\Gr4vy\PazeShippingAddress  $shippingAddress
     * @phpstan-pure
     */
    public function __construct(PazeConsumer $consumer, PazeMaskedCard $maskedCard, PazeSessionReviewLinks $links, string $code, ?PazeShippingAddress $shippingAddress = null)
    {
        $this->consumer = $consumer;
        $this->maskedCard = $maskedCard;
        $this->links = $links;
        $this->code = $code;
        $this->shippingAddress = $shippingAddress;
    }
}