<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class RepayBankOptions
{
    /**
     * The Nacha Standard Entry Class code describing how the account holder authorized an ACH debit. When omitted, `TelDebit` is used for a `moto` payment source and `WebDebit` otherwise. Ignored for business accounts, which Repay requires to use `CcdDebit`.
     *
     * @var ?string $secCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sec_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $secCode = null;

    /**
     * @param  ?string  $secCode
     * @phpstan-pure
     */
    public function __construct(?string $secCode = null)
    {
        $this->secCode = $secCode;
    }
}