<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class TransactionsReportSpec
{
    /**
     * The parameters for the transactions report model.
     *
     * @var array<string, mixed> $params
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('params')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>')]
    public array $params;

    /**
     * The report model type.
     *
     * @var ?string $model
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('model')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $model = null;

    /**
     * @param  array<string, mixed>  $params
     * @param  ?string  $model
     * @phpstan-pure
     */
    public function __construct(array $params, ?string $model = 'transactions')
    {
        $this->params = $params;
        $this->model = $model;
    }
}