<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class TravelHubCustomData
{
    /**
     * The key of the custom data field.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The value of the custom data field.
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * The type of the custom data field.
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * @param  string  $name
     * @param  string  $value
     * @param  ?string  $type
     * @phpstan-pure
     */
    public function __construct(string $name, string $value, ?string $type = null)
    {
        $this->name = $name;
        $this->value = $value;
        $this->type = $type;
    }
}