<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gr4vy;


class WpayEverdaypayOptions
{
    /**
     * A dictionary of merchant defined data, to be passed to Wpay for anti-fraud control.
     *
     * @var ?array<string, string> $merchantDefinedData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchant_defined_data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $merchantDefinedData = null;

    /**
     * The customer ID for the Everyday Rewards account.
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * The access token for the Everyday Rewards account.
     *
     * @var ?string $rewardsAccessToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rewardsAccessToken')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $rewardsAccessToken = null;

    /**
     * The ID of the device on which the payment is occuring.
     *
     * @var ?string $deviceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deviceId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $deviceId = null;

    /**
     * Whether the transaction should redirect post-payment
     *
     * @var ?bool $postPaymentRedirect
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postPaymentRedirect')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $postPaymentRedirect = null;

    /**
     * @param  ?array<string, string>  $merchantDefinedData
     * @param  ?string  $customerId
     * @param  ?string  $rewardsAccessToken
     * @param  ?string  $deviceId
     * @param  ?bool  $postPaymentRedirect
     * @phpstan-pure
     */
    public function __construct(?array $merchantDefinedData = null, ?string $customerId = null, ?string $rewardsAccessToken = null, ?string $deviceId = null, ?bool $postPaymentRedirect = null)
    {
        $this->merchantDefinedData = $merchantDefinedData;
        $this->customerId = $customerId;
        $this->rewardsAccessToken = $rewardsAccessToken;
        $this->deviceId = $deviceId;
        $this->postPaymentRedirect = $postPaymentRedirect;
    }
}