name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    # “At 08:30 on every day-of-week from Monday through Friday.”
    - cron: 30 8 * * 1-5

jobs:
  test:
    runs-on: ubuntu-latest
    
    timeout-minutes: 3
    strategy:
      matrix:
        php:
          - 8.x

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use PHP ${{ matrix.php }}
        uses: actions/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
      - uses: "ramsey/composer-install@v3"

      - name: Run tests
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          composer test

      - uses: hmarr/auto-approve-action@v4
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        with:
          github-token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

  merge:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: automerge
        name: automerge
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          MERGE_LABELS: ''
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_ERROR_FAIL: true
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: false
          UPDATE_METHOD: rebase