name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use PHP Composer
        uses: php-actions/composer@v6

      - name: Install dependencies
        run: |
          composer require gr4vy/gr4vy-php
          composer install

      - name: Run tests
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          ./vendor/bin/phpunit test/
