name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    # “At 08:30 on every day-of-week from Monday through Friday.”
    - cron: 30 8 * * 1-5

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 3
    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"

      - name: Run tests
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          composer test

      - uses: hmarr/auto-approve-action@v4
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        with:
          github-token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

  merge:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: automerge
        name: automerge
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_ERROR_FAIL: true
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: false
          UPDATE_METHOD: rebase

  notify:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ contains(needs.*.result, 'failure') }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'github-actions[bot]')
        env:
            SLACK_USERNAME: PHP SDK 
            SLACK_TITLE: PHP SDK
            SLACK_WEBHOOK: ${{ secrets.SLACK_SDK_WEBHOOK_URL }}
            SLACK_CHANNEL: sdk-updates
            SLACK_MSG_AUTHOR: gr4vy-code
            SLACK_ICON_EMOJI: ":gr4vy:"
            SLACK_COLOR: "${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}"
            SLACK_MESSAGE_ON_SUCCESS: "CI passed"
            SLACK_MESSAGE_ON_FAILURE: "CI failed"
            SLACK_FOOTER: ""
