name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        uses: php-actions/composer@v6
        with:
          php_version: 7.3.24
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          ./vendor/bin/phpunit test/
